# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('date_created',)},
        ),
        migrations.AddField(
            model_name='project',
            name='deletable',
            field=models.BooleanField(default=True),
        ),
    ]
