# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SSHKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField()),
                ('owner', models.SlugField()),
                ('public', models.TextField()),
                ('fingerprint', models.TextField(max_length=500, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('date_created',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='sshkey',
            unique_together=set([('name', 'owner')]),
        ),
    ]
