# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField()),
                ('deletable', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('owner', models.SlugField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='vpc',
            unique_together=set([('name', 'owner')]),
        ),
    ]
